on:
  push:
    branches:
      - jfirebaugh
    tags:
      - v*.*.*
  pull_request:

name: Testing

permissions:
  id-token: write
  contents: read

jobs:
  linux-tests:
    name: "Linux Tests"
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22, 24]
    runs-on: ubuntu-22.04
    container: ubuntu:20.04
    steps:
      - name: Install Dependencies for Ubuntu
        run: apt-get update && apt-get install -y git build-essential clang-14 libssl-dev libkrb5-dev libc++-14-dev libc++abi-14-dev wget python3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          set -e
          mkdir ~/.ssh_tests
          chmod 700 ~/.ssh_tests
          printf "%b" "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh_tests/config
          cat test/id_rsa.pub > ~/.ssh_tests/id_rsa.pub
          cat test/id_rsa.enc | base64 -d > ~/.ssh_tests/id_rsa
          chmod 600 ~/.ssh_tests/id_rsa*
          git config --global user.name "John Doe"
          git config --global user.email johndoe@example.com

      - name: Use Node.js
        uses: actions/setup-node@v4
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install
        env:
          CC: clang-14
          CXX: clang++-14
          npm_config_clang: 1
          GYP_DEFINES: use_obsolete_asm=true
        # There is a race condition in node/generate that needs to be fixed
        # Node 16 changed the logic it uses to select it's UID which means to make node run as root and not 1001, we need to chwon the current directory. More Details:
        # https://stackoverflow.com/questions/70298238/getting-eaccess-when-running-npm-8-as-root
        run: |
          chown root.root -R .
          npm set unsafe-perm true || true
          node utils/retry npm install

      - name: Test
        run: |
          set -e
          eval `ssh-agent -s`
          ssh-add ~/.ssh_tests/id_rsa
          node utils/retry npm test

      - name: configure aws credentials
        if: startsWith(github.ref, 'refs/tags/v')
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::060562746757:role/nodegit-repository
          aws-region: us-west-2

      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          npm install -g @mapbox/node-pre-gyp aws-sdk
          node lifecycleScripts/clean
          node-pre-gyp package
          node-pre-gyp publish

  macos-tests:
    name: "macOS Tests"
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22, 24]
        os: [macos-13-xlarge]
    runs-on: ${{ matrix.os }}
  # This is mostly the same as the Linux steps, waiting for anchor support
  # https://github.com/actions/runner/issues/1182
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          mkdir ~/.ssh_tests
          chmod 700 ~/.ssh_tests
          printf "%b" "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh_tests/config
          cat test/id_rsa.pub > ~/.ssh_tests/id_rsa.pub
          cat test/id_rsa.enc | base64 -d > ~/.ssh_tests/id_rsa
          chmod 600 ~/.ssh_tests/id_rsa*
          git config --global user.name "John Doe"
          git config --global user.email johndoe@example.com

      - name: Use Node.js
        uses: actions/setup-node@v4
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install
        env:
          CC: clang
          CXX: clang++
          npm_config_clang: 1
          GYP_DEFINES: use_obsolete_asm=true
        # There is a race condition in node/generate that needs to be fixed
        run: node utils/retry npm install

      - name: Test
        run: |
          set -e
          eval `ssh-agent -s`
          ssh-add ~/.ssh_tests/id_rsa
          node utils/retry npm test

      - name: configure aws credentials
        if: startsWith(github.ref, 'refs/tags/v')
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::060562746757:role/nodegit-repository
          aws-region: us-west-2

      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          npm install -g @mapbox/node-pre-gyp aws-sdk
          node lifecycleScripts/clean
          node-pre-gyp package
          node-pre-gyp publish
